language: node_js
node_js:
  - "4.4"
  - "5.11"
  - "6.1"
sudo: false
cache:
  directories:
    - node_modules
script: "npm run-script test-ci"
after_script: "npm i coveralls && cat ./coverage/lcov.info | coveralls"
