#### aglex config

## AWS credential and region
config:
  ## Profile name for AWS CLI (see: AWS.SharedIniFileCredentials)
  # profile: prod

  ## You can also specify accessKeyId/secretAccessKey
  # accessKeyId: YOUR_AWS_ACCESS_KEY
  # secretAccessKey: YOUR_AWS_SECRET_KEY

  # Region name for AWS (e.g. us-east-1)
  region: us-east-1

## Lambda configuration
lambda:
  Handler: lambda.handler
  Runtime: nodejs4.3
  MemorySize: 128
  Timeout: 60
  FunctionName: YOUR_LAMBDA_FUNCTION_NAME
  Description: YOUR_LAMBDA_DESCRIPTION
  RoleName: YOUR_LAMBDA_EXECUTION_ROLE # Role ARN will generate from RoleName automatically

## API Gateway configuration
apiGateway:
  swagger: 2.0
  info:
    title: YOUR_API_NAME
    description: YOUR_API_DESCRIPTION
  basePath: /prod
  schemes:
    - https
  paths:
    /{proxy+}:
      x-amazon-apigateway-any-method:
        produces:
          - application/json
        parameters:
          - name: proxy
            in: path
            required: true
            type: string
        responses:
          200:
            description: 200 response
            schema:
              $ref: "#/definitions/Empty"
        x-amazon-apigateway-integration:
          httpMethod: POST
          passthroughBehavior: when_no_match
          responses:
            default:
              statusCode: 200
          type: aws_proxy
          uri: REPLACED_AUTOMATICALLY_WITH_YOUR_LAMBDA_INVOCATION_ARN
  definitions:
    Empty:
      title: Empty Schema
      type: object
